<?php
use Dfi\TestUtils\Module\Map;
use TestLib\Mink;
use TestLib\PhantomJs;

/**
 * Created by IntelliJ IDEA.
 * User: z.wieczorek
 * Date: 29.10.15
 * Time: 13:35
 */
abstract class AbstractTest extends PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        parent::setUp();
        define('ROOT', getcwd());

        define('TEST_HOST', 'file://' . getcwd() . '/tests/fixtures/html/admin-collected-list.html');

        $file = 'tests/fixtures/module-map.json';

        $phantom = PhantomJs::getInstance();
        $mink = Mink::getInstance();
        $mink->setUp($phantom->getPort());

        Map::setHost('tests/fixtures');
        Map::setConfigFile($file);
        Map::generate();
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }


}